build:
	gcc -Wall -Wextra -c triefuns.c
	gcc -Wall -Wextra -c books.c
	gcc -Wall -Wextra -c author.c
	gcc -Wall -Wextra -c trie.c
	gcc triefuns.o books.o author.o trie.o -o tema3	
clean:
	rm -rf *.o tema3
